# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f0fbe926ea3ae8db1b48beaea97bfe3667ec66e6b1a24fa961907817a431fe5b99008bf2fdf55bcf6516e969f8321352e83bcabd437dae3118b1358f0d796e

test:
  secret_key_base: 9f6522f29ccd2ad88be354b04c8b6e6eccb3cf6a364f263f13f482c2c53ff3da8be6ab333da03fe9a4ec497c6b5aa0ac84961f5fcaa55311edf81fd12dbb7022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
